export interface InstitutionOption {
  name: string;
  category:
    | "public_uni"
    | "private_uni"
    | "specialized"
    | "national_poly"
    | "tvet"
    | "college"
    | "proprietary";
  region: string;
}

export const KENYAN_INSTITUTIONS: InstitutionOption[] = [
  // =============================================
  // PUBLIC CHARTERED UNIVERSITIES (36)
  // =============================================
  { name: "University of Nairobi (UoN)", category: "public_uni", region: "Nairobi" },
  { name: "Kenyatta University (KU)", category: "public_uni", region: "Nairobi / Kiambu" },
  {
    name: "Jomo Kenyatta University of Agriculture and Technology (JKUAT)",
    category: "public_uni",
    region: "Kiambu",
  },
  { name: "Technical University of Kenya (TUK)", category: "public_uni", region: "Nairobi" },
  { name: "Multimedia University of Kenya (MMU)", category: "public_uni", region: "Nairobi" },
  { name: "The Co-operative University of Kenya (CUK)", category: "public_uni", region: "Nairobi" },
  { name: "Moi University", category: "public_uni", region: "Uasin Gishu" },
  { name: "University of Eldoret (UoE)", category: "public_uni", region: "Uasin Gishu" },
  { name: "Egerton University", category: "public_uni", region: "Nakuru" },
  {
    name: "Dedan Kimathi University of Technology (DeKUT)",
    category: "public_uni",
    region: "Nyeri",
  },
  { name: "Karatina University", category: "public_uni", region: "Nyeri" },
  { name: "Murang'a University of Technology (MUT)", category: "public_uni", region: "Murang'a" },
  { name: "Kirinyaga University", category: "public_uni", region: "Kirinyaga" },
  { name: "University of Embu", category: "public_uni", region: "Embu" },
  { name: "Chuka University", category: "public_uni", region: "Tharaka Nithi" },
  { name: "Tharaka University", category: "public_uni", region: "Tharaka Nithi" },
  {
    name: "Meru University of Science and Technology (MUST)",
    category: "public_uni",
    region: "Meru",
  },
  { name: "Machakos University", category: "public_uni", region: "Machakos" },
  { name: "South Eastern Kenya University (SEKU)", category: "public_uni", region: "Kitui" },
  { name: "Technical University of Mombasa (TUM)", category: "public_uni", region: "Mombasa" },
  { name: "Pwani University", category: "public_uni", region: "Kilifi" },
  { name: "Taita Taveta University", category: "public_uni", region: "Taita Taveta" },
  { name: "Garissa University", category: "public_uni", region: "Garissa" },
  { name: "Maseno University", category: "public_uni", region: "Kisumu" },
  {
    name: "Jaramogi Oginga Odinga University of Science and Technology (JOOUST)",
    category: "public_uni",
    region: "Siaya",
  },
  {
    name: "Masinde Muliro University of Science and Technology (MMUST)",
    category: "public_uni",
    region: "Kakamega",
  },
  { name: "Kaimosi Friends University", category: "public_uni", region: "Vihiga" },
  { name: "Kibabii University", category: "public_uni", region: "Bungoma" },
  { name: "Alupe University", category: "public_uni", region: "Busia" },
  { name: "Kisii University", category: "public_uni", region: "Kisii" },
  { name: "Rongo University", category: "public_uni", region: "Migori" },
  { name: "Tom Mboya University", category: "public_uni", region: "Homa Bay" },
  { name: "Maasai Mara University", category: "public_uni", region: "Narok" },
  { name: "University of Kabianga", category: "public_uni", region: "Kericho" },
  { name: "Laikipia University", category: "public_uni", region: "Laikipia" },
  { name: "Bomet University", category: "public_uni", region: "Bomet" },

  // =============================================
  // PRIVATE CHARTERED UNIVERSITIES (32)
  // =============================================
  { name: "Strathmore University", category: "private_uni", region: "Nairobi" },
  {
    name: "United States International University - Africa (USIU)",
    category: "private_uni",
    region: "Nairobi",
  },
  {
    name: "Catholic University of Eastern Africa (CUEA)",
    category: "private_uni",
    region: "Nairobi",
  },
  { name: "Daystar University", category: "private_uni", region: "Nairobi / Machakos" },
  { name: "KCA University", category: "private_uni", region: "Nairobi" },
  { name: "Mount Kenya University (MKU)", category: "private_uni", region: "Kiambu" },
  { name: "Zetech University", category: "private_uni", region: "Kiambu" },
  { name: "Africa Nazarene University (ANU)", category: "private_uni", region: "Kajiado" },
  { name: "Kenya Methodist University (KeMU)", category: "private_uni", region: "Meru" },
  { name: "St. Paul's University", category: "private_uni", region: "Kiambu" },
  { name: "Pan Africa Christian University (PAC)", category: "private_uni", region: "Nairobi" },
  { name: "Kabarak University", category: "private_uni", region: "Nakuru" },
  { name: "University of Eastern Africa, Baraton", category: "private_uni", region: "Nandi" },
  { name: "Scott Christian University", category: "private_uni", region: "Machakos" },
  { name: "Africa International University (AIU)", category: "private_uni", region: "Nairobi" },
  { name: "Kenya Highlands Evangelical University", category: "private_uni", region: "Kericho" },
  { name: "Great Lakes University of Kisumu", category: "private_uni", region: "Kisumu" },
  { name: "Adventist University of Africa", category: "private_uni", region: "Kajiado" },
  { name: "KAG EAST University", category: "private_uni", region: "Kajiado" },
  { name: "Umma University", category: "private_uni", region: "Kajiado" },
  {
    name: "Presbyterian University of East Africa (PUEA)",
    category: "private_uni",
    region: "Kiambu",
  },
  { name: "Aga Khan University", category: "private_uni", region: "Nairobi" },
  {
    name: "Kiriri Women's University of Science and Technology",
    category: "private_uni",
    region: "Nairobi",
  },
  { name: "The East African University", category: "private_uni", region: "Kajiado" },
  { name: "Lukenya University", category: "private_uni", region: "Makueni" },
  { name: "Management University of Africa (MUA)", category: "private_uni", region: "Nairobi" },
  { name: "Tangaza University", category: "private_uni", region: "Nairobi" },
  { name: "Islamic University of Kenya", category: "private_uni", region: "Kajiado" },
  { name: "Riara University", category: "private_uni", region: "Nairobi" },
  { name: "Uzima University", category: "private_uni", region: "Kisumu" },
  { name: "Gretsa University", category: "private_uni", region: "Kiambu" },
  { name: "Amref International University", category: "private_uni", region: "Nairobi" },

  // =============================================
  // SPECIALIZED PUBLIC UNIVERSITIES (3)
  // =============================================
  { name: "National Defence University–Kenya", category: "specialized", region: "Nakuru" },
  { name: "Open University of Kenya", category: "specialized", region: "Machakos" },
  { name: "National Intelligence Research University", category: "specialized", region: "Nairobi" },

  // =============================================
  // NATIONAL POLYTECHNICS (10)
  // =============================================
  { name: "The Kenya Coast National Polytechnic", category: "national_poly", region: "Mombasa" },
  { name: "Kabete National Polytechnic", category: "national_poly", region: "Nairobi" },
  {
    name: "Nairobi Technical Training Institute (NTTI)",
    category: "national_poly",
    region: "Nairobi",
  },
  { name: "Kisumu National Polytechnic", category: "national_poly", region: "Kisumu" },
  { name: "Eldoret National Polytechnic", category: "national_poly", region: "Uasin Gishu" },
  { name: "Nyeri National Polytechnic", category: "national_poly", region: "Nyeri" },
  { name: "Meru National Polytechnic", category: "national_poly", region: "Meru" },
  { name: "Sigalagala National Polytechnic", category: "national_poly", region: "Kakamega" },
  { name: "Kitale National Polytechnic", category: "national_poly", region: "Trans Nzoia" },
  { name: "Machakos Technical Training Institute", category: "national_poly", region: "Machakos" },

  // =============================================
  // TVET INSTITUTIONS
  // =============================================
  { name: "Ambritch College of Technology", category: "tvet", region: "Nairobi" },
  { name: "East Africa Institute of Certified Studies", category: "tvet", region: "Nairobi" },
  { name: "Talanta Institute", category: "tvet", region: "Nairobi" },
  { name: "African International Technical College (AITEC)", category: "tvet", region: "Nairobi" },
  { name: "Africa Digital Media Institute (ADMI)", category: "tvet", region: "Nairobi" },
  { name: "AirSwiss International College", category: "tvet", region: "Nairobi" },
  { name: "Divas Technology College", category: "tvet", region: "Kilifi" },
  {
    name: "Amboseli Institute of Hospitality and Technology",
    category: "tvet",
    region: "Thika / Nakuru",
  },
  { name: "Nairobi Institute of Software Development", category: "tvet", region: "Nairobi" },
  { name: "NairoBits College", category: "tvet", region: "Nairobi" },
  { name: "Nairobi Industrial Institute College", category: "tvet", region: "Nairobi" },
  { name: "Kenya Coffee School", category: "tvet", region: "Nairobi" },
  {
    name: "Barista Coffee Skills and Technology Training Institute",
    category: "tvet",
    region: "Nairobi",
  },
  { name: "Atlas College", category: "tvet", region: "Nairobi" },
  {
    name: "Kenya Institute of Highways and Building Technology (KIHBT)",
    category: "tvet",
    region: "Nairobi",
  },
  { name: "Adept College of Professional Studies", category: "tvet", region: "Nakuru" },
  {
    name: "African Institute of Research and Development Studies (AIRDES)",
    category: "tvet",
    region: "Mombasa",
  },
  { name: "Bandari College", category: "tvet", region: "Mombasa" },
  { name: "Baraton Teachers' Training College", category: "tvet", region: "Nandi" },
  { name: "Bungoma North Technical Vocational College", category: "tvet", region: "Bungoma" },
  { name: "Consolata Cathedral Institute", category: "tvet", region: "Nyeri" },
  { name: "Cascade Institute of Hospitality", category: "tvet", region: "Thika" },
  { name: "Eldoret Technical Training Institute", category: "tvet", region: "Uasin Gishu" },
  { name: "Eldoret Polytechnic", category: "tvet", region: "Uasin Gishu" },
  { name: "Emma Daniel Arts Training Institute (EDATI)", category: "tvet", region: "Nairobi" },
  { name: "Government Training Institute (GTI)", category: "tvet", region: "Nairobi" },
  { name: "Gusii Institute of Technology", category: "tvet", region: "Kisii" },
  { name: "Harvard Institute of Development Studies", category: "tvet", region: "Thika" },
  {
    name: "Hemland College of Professional and Technical Studies",
    category: "tvet",
    region: "Thika",
  },
  { name: "ICT Fire and Rescue", category: "tvet", region: "Thika" },
  { name: "Indian Institute of Hardware Technology (IIHT)", category: "tvet", region: "Nairobi" },
  { name: "International Centre of Technology (ICT-Thika)", category: "tvet", region: "Thika" },
  { name: "Intraglobal Training Institute - Nairobi CBD", category: "tvet", region: "Nairobi" },
  { name: "Intraglobal Training Institute - Kisumu", category: "tvet", region: "Kisumu" },
  { name: "Intraglobal Training Institute - Kisii", category: "tvet", region: "Kisii" },
  { name: "Intraglobal Training Institute - Embu", category: "tvet", region: "Embu" },
  { name: "Intraglobal Training Institute - Nakuru", category: "tvet", region: "Nakuru" },
  { name: "Intraglobal Training Institute - Donholm", category: "tvet", region: "Nairobi" },
  { name: "Jaffery Institute of Professional Studies", category: "tvet", region: "Mombasa" },
  { name: "Kagumo College", category: "tvet", region: "Nyeri" },
  { name: "Kaiboi Technical Training Institute", category: "tvet", region: "Nakuru" },
  { name: "The Kenya College of Science and Technology", category: "tvet", region: "Nairobi" },
  { name: "Kenya Forestry College", category: "tvet", region: "Kericho" },
  { name: "Kenya School of Government (KSG)", category: "tvet", region: "Nairobi" },
  {
    name: "Kenya Institute of Biomedical Sciences and Technology (KIBSAT)",
    category: "tvet",
    region: "Nakuru",
  },
  { name: "Kenya Institute of Management (KIM)", category: "tvet", region: "Nairobi" },
  { name: "Kenya Institute of Mass Communication (KIMC)", category: "tvet", region: "Nairobi" },
  {
    name: "Kenya Institute of Monitoring and Evaluation Studies (KIMES)",
    category: "tvet",
    region: "Nakuru",
  },
  { name: "Kenya Institute of Software Engineering", category: "tvet", region: "Thika" },
  { name: "Kenya School of Medical Science and Technology", category: "tvet", region: "Nairobi" },
  { name: "Kenya School of Monetary Studies", category: "tvet", region: "Nairobi" },
  { name: "Kenya Science Teachers College", category: "tvet", region: "Nairobi" },
  { name: "Kenya Technical Teachers College (KTTC)", category: "tvet", region: "Nairobi" },
  { name: "Kenya Water Institute", category: "tvet", region: "Nairobi" },
  { name: "Kenya Wildlife Service Training Institute", category: "tvet", region: "Naivasha" },
  { name: "Kiambu Institute of Science and Technology", category: "tvet", region: "Kiambu" },
  { name: "Kigari Teachers College", category: "tvet", region: "Embu" },
  { name: "Kilimambogo Teachers College", category: "tvet", region: "Machakos" },
  {
    name: "Kipkabus Technical and Vocational College (KTVC)",
    category: "tvet",
    region: "Uasin Gishu",
  },
  { name: "Kisumu Polytechnic", category: "tvet", region: "Kisumu" },
  { name: "Kitale Technical Institute", category: "tvet", region: "Trans Nzoia" },
  { name: "Machakos Institute of Technology", category: "tvet", region: "Machakos" },
  { name: "Mboya Labour College", category: "tvet", region: "Kisumu" },
  { name: "Michuki Technical Institute", category: "tvet", region: "Murang'a" },
  { name: "Nairobi Aviation College - Kisumu Campus", category: "tvet", region: "Kisumu" },
  { name: "Nakuru Counselling & Training Institute", category: "tvet", region: "Nakuru" },
  {
    name: "PC Kinyanjui Technical Training Institute (PCKTTI)",
    category: "tvet",
    region: "Nairobi",
  },
  { name: "Railway Training Institute", category: "tvet", region: "Nairobi" },
  { name: "Ramogi Institute of Advanced Technology", category: "tvet", region: "Kisumu" },
  { name: "Rifkins College", category: "tvet", region: "Mombasa" },
  { name: "Rift Valley Technical Training Institute", category: "tvet", region: "Nakuru" },
  { name: "Sacred Training Institute", category: "tvet", region: "Bungoma / Nairobi" },
  { name: "Savannah Institute for Business and Informatics", category: "tvet", region: "Nakuru" },
  { name: "Sensei Institute of Technology", category: "tvet", region: "Nakuru" },
  { name: "Sirisia Youth Polytechnic", category: "tvet", region: "Bungoma" },
  { name: "Technical Training Institute (MTTI)", category: "tvet", region: "Mombasa" },
  { name: "Thika Technical Training Institute", category: "tvet", region: "Thika" },
  { name: "United Africa College", category: "tvet", region: "Nairobi" },
  { name: "Rift Valley Institute of Science & Technology", category: "tvet", region: "Nakuru" },
  { name: "Vision Empowerment Training Institute - Nairobi", category: "tvet", region: "Nairobi" },
  {
    name: "Vision Empowerment Training Institute - Kitengela",
    category: "tvet",
    region: "Kajiado",
  },
  { name: "Vision Stars Training Institute", category: "tvet", region: "Nairobi" },
  { name: "Visualdo Institute", category: "tvet", region: "Nairobi" },
  { name: "Kenya Institute of Development Studies (KIDS)", category: "tvet", region: "Nairobi" },
  {
    name: "Kenya Christian Industrial Training Institute (KCITI)",
    category: "tvet",
    region: "Nairobi",
  },
  { name: "Kenya School of Law", category: "tvet", region: "Nairobi" },
  { name: "Meru University TVET", category: "tvet", region: "Meru" },

  // =============================================
  // COLLEGES (Medical, Teachers, etc.)
  // =============================================
  { name: "KMTC - Nairobi Campus", category: "college", region: "Nairobi" },
  { name: "KMTC - Mombasa Campus", category: "college", region: "Mombasa" },
  { name: "KMTC - Nakuru Campus", category: "college", region: "Nakuru" },
  { name: "KMTC - Kisumu Campus", category: "college", region: "Kisumu" },
  { name: "KMTC - Eldoret Campus", category: "college", region: "Uasin Gishu" },
  { name: "KMTC - Nyeri Campus", category: "college", region: "Nyeri" },
  { name: "KMTC - Kilifi Campus", category: "college", region: "Kilifi" },
  { name: "Kenya Utalii College", category: "college", region: "Nairobi" },
  { name: "St. Joseph's Medical Training College", category: "college", region: "Kisumu" },
  { name: "St. Mary's School of Clinical Medicine", category: "college", region: "Kakamega" },
  { name: "Kenya Aeronautical College", category: "college", region: "Nairobi" },
  { name: "Nairobi Aviation College", category: "college", region: "Nairobi" },
  { name: "East African School of Aviation", category: "college", region: "Nairobi" },
  { name: "Skypath Aviation College", category: "college", region: "Nairobi" },
  { name: "Eagle Air Aviation College (EAAC)", category: "college", region: "Kajiado" },
  { name: "Eldoret Aviation Training Institute", category: "college", region: "Uasin Gishu" },
  { name: "Kericho Teachers College", category: "college", region: "Kericho" },
  { name: "Migori Teachers College", category: "college", region: "Migori" },
  { name: "Mosoriot Teachers College", category: "college", region: "Uasin Gishu" },
  { name: "Narok Teachers College", category: "college", region: "Narok" },
  { name: "Shanzu Teachers College", category: "college", region: "Mombasa" },
  { name: "Tambach Teachers Training College", category: "college", region: "Elgeyo Marakwet" },
  { name: "Nkabune Technical Institute", category: "college", region: "Meru" },
  { name: "Mawego Technical Institute", category: "college", region: "Homa Bay" },
  { name: "Murang'a Institute of Technology", category: "college", region: "Murang'a" },
  { name: "Sagana Institute of Technology", category: "college", region: "Kirinyaga" },
  { name: "Karatina Institute of Technology (KIT)", category: "college", region: "Nyeri" },
  { name: "Meru Technical Institute", category: "college", region: "Meru" },
  { name: "Nairobi Institute of Business Studies (NIBS)", category: "college", region: "Nairobi" },
  { name: "National Youth Service Engineering Institute", category: "college", region: "Nairobi" },

  // =============================================
  // PROPRIETARY / PRIVATE COLLEGES & INSTITUTES
  // =============================================
  { name: "Africa College of Social Work", category: "proprietary", region: "Nairobi" },
  { name: "Airways Travel Institute", category: "proprietary", region: "Nairobi" },
  { name: "Alphax College", category: "proprietary", region: "Uasin Gishu" },
  { name: "Amani College", category: "proprietary", region: "Nairobi" },
  { name: "Arkline College", category: "proprietary", region: "Nairobi" },
  { name: "Associated Computer Services", category: "proprietary", region: "Nairobi" },
  { name: "AUGAB Computer College", category: "proprietary", region: "Garissa" },
  { name: "Augustana College", category: "proprietary", region: "Nairobi" },
  { name: "Australian Studies Institute (AUSI)", category: "proprietary", region: "Nairobi" },
  { name: "Bell Institute of Technology", category: "proprietary", region: "Nairobi" },
  { name: "Belmont International College", category: "proprietary", region: "Kajiado" },
  { name: "Bible College of East Africa", category: "proprietary", region: "Nairobi" },
  { name: "BizSmart Inter Technology", category: "proprietary", region: "Nairobi" },
  { name: "Bungoma Technical Training Institute", category: "proprietary", region: "Bungoma" },
  { name: "Career Training Centre", category: "proprietary", region: "Nairobi" },
  { name: "Century Park College", category: "proprietary", region: "Machakos" },
  { name: "Coast Institute of Technology", category: "proprietary", region: "Mombasa" },
  { name: "College of Management Sciences", category: "proprietary", region: "Nairobi" },
  { name: "Compuera College", category: "proprietary", region: "Nairobi" },
  { name: "Compugoal College", category: "proprietary", region: "Nairobi" },
  { name: "Computer Learning Centre (CLC)", category: "proprietary", region: "Nairobi" },
  { name: "Computer Pride Training Centre", category: "proprietary", region: "Nairobi" },
  { name: "Newview College", category: "proprietary", region: "Nairobi" },
  {
    name: "Consolata Institute of Communication and Technology",
    category: "proprietary",
    region: "Nyeri",
  },
  { name: "Cornerstone Training Institute", category: "proprietary", region: "Nairobi" },
  { name: "Dairy Training Institute Naivasha (DTI)", category: "proprietary", region: "Nakuru" },
  { name: "Digital Resource Center (DRC)", category: "proprietary", region: "Nakuru" },
  { name: "Digiworld Computer School", category: "proprietary", region: "Meru" },
  { name: "Don Bosco Boys' Town", category: "proprietary", region: "Nairobi" },
  { name: "Don Bosco Institute of Management Studies", category: "proprietary", region: "Nairobi" },
  { name: "Duolotech Computers", category: "proprietary", region: "Kiambu / Thika" },
  { name: "Eagle College of Management Studies", category: "proprietary", region: "Nairobi" },
  { name: "East Africa School of Journalism (EASJ)", category: "proprietary", region: "Nairobi" },
  { name: "East Africa School of Management", category: "proprietary", region: "Nairobi" },
  { name: "East Africa Vision Institute", category: "proprietary", region: "Nairobi" },
  { name: "East African Media Institute (EAMI)", category: "proprietary", region: "Nairobi" },
  { name: "Elite Centre", category: "proprietary", region: "Nairobi / Nakuru" },
  { name: "Elite Commercial Institute", category: "proprietary", region: "Nairobi" },
  { name: "Elix Centre of Informatics", category: "proprietary", region: "Turkana" },
  { name: "Emanex Computer College", category: "proprietary", region: "Nairobi" },
  { name: "Esmart College", category: "proprietary", region: "Kiambu" },
  { name: "Felma College", category: "proprietary", region: "Nairobi" },
  { name: "German Institute of Professional Studies", category: "proprietary", region: "Nairobi" },
  { name: "Globoville Shanzu Beach College", category: "proprietary", region: "Mombasa" },
  { name: "Graffins College", category: "proprietary", region: "Nairobi" },
  { name: "Hansons College of Professional Studies", category: "proprietary", region: "Nairobi" },
  { name: "Hemland Computer Institute", category: "proprietary", region: "Thika" },
  { name: "Hi-tec Institute of Professional Studies", category: "proprietary", region: "Mombasa" },
  { name: "Higher Institute of Development Studies", category: "proprietary", region: "Nairobi" },
  { name: "Holy Rosary College", category: "proprietary", region: "Machakos" },
  { name: "The iNet College", category: "proprietary", region: "Bungoma" },
  { name: "Institute of Advanced Technology", category: "proprietary", region: "Nairobi" },
  { name: "Institute of Business and Technology", category: "proprietary", region: "Nakuru" },
  {
    name: "Institute of Information Technology Studies & Research",
    category: "proprietary",
    region: "Nairobi",
  },
  { name: "Institute of Zaburi Technologies", category: "proprietary", region: "Nairobi" },
  { name: "Inter-Afrika Development Institute", category: "proprietary", region: "Nairobi" },
  { name: "International College of Kenya", category: "proprietary", region: "Nairobi / Machakos" },
  { name: "International Hotel & Tourism Institute", category: "proprietary", region: "Nairobi" },
  { name: "InterWorld College", category: "proprietary", region: "Nairobi" },
  { name: "Jodan College of Technology", category: "proprietary", region: "Thika" },
  { name: "Jogoo Commercial College", category: "proprietary", region: "Nakuru" },
  { name: "Keiway Mining & Technology College", category: "proprietary", region: "Kilifi" },
  {
    name: "Kenair Travel and Related Studies",
    category: "proprietary",
    region: "Nairobi / Mombasa",
  },
  {
    name: "Kenya College of Communications Technology",
    category: "proprietary",
    region: "Nairobi",
  },
  {
    name: "Kenya College of Medicine & Related Studies",
    category: "proprietary",
    region: "Nairobi",
  },
  {
    name: "Kenya College of Skills and Talent Development",
    category: "proprietary",
    region: "Nairobi",
  },
  { name: "Kenya Institute of Applied Sciences", category: "proprietary", region: "Nairobi" },
  {
    name: "Kenya Institute of Media and Technology (KIMT)",
    category: "proprietary",
    region: "Nairobi",
  },
  { name: "Kenya Institute of Professional Studies", category: "proprietary", region: "Nairobi" },
  {
    name: "Kenya Institute of Social Work and Community Development (KISWCD)",
    category: "proprietary",
    region: "Nairobi",
  },
  {
    name: "Kenya Institute of Special Education (KISE)",
    category: "proprietary",
    region: "Nairobi",
  },
  {
    name: "Kenya School of Accountancy and Finance",
    category: "proprietary",
    region: "Trans Nzoia / Kisii",
  },
  {
    name: "Kenya School of Professional Counseling & Behavioural Sciences",
    category: "proprietary",
    region: "Nairobi",
  },
  {
    name: "Kenya School of Professional Studies (KSPS)",
    category: "proprietary",
    region: "Nairobi",
  },
  { name: "Kenya School of Technology Studies (KSTS)", category: "proprietary", region: "Thika" },
  {
    name: "Kima International School of Theology (KIST)",
    category: "proprietary",
    region: "Vihiga",
  },
  { name: "Kinyanjui Technical Training Institute", category: "proprietary", region: "Nairobi" },
  {
    name: "Lake Region Business Training and Consultancy",
    category: "proprietary",
    region: "Nakuru",
  },
  { name: "Lakeview Training Institute", category: "proprietary", region: "Nakuru" },
  { name: "Language School in Kenya", category: "proprietary", region: "Nairobi" },
  { name: "Maxton College of Media & Communications", category: "proprietary", region: "Nairobi" },
  { name: "Motion City International", category: "proprietary", region: "Nairobi" },
  {
    name: "Naivasha Computer & Business Studies College",
    category: "proprietary",
    region: "Nakuru",
  },
  {
    name: "Nakuru College of Health Sciences and Management",
    category: "proprietary",
    region: "Nakuru",
  },
  {
    name: "Nakuru Institute of Information Communication Technology",
    category: "proprietary",
    region: "Nakuru",
  },
  {
    name: "Nationwide Hotel and Tourism College (NHTC)",
    category: "proprietary",
    region: "Nakuru",
  },
  { name: "Neema Lutheran College", category: "proprietary", region: "Nyamira" },
  { name: "Oshwal College", category: "proprietary", region: "Nairobi" },
  { name: "Pan African School of Theology (PAST)", category: "proprietary", region: "Nyandarua" },
  { name: "PCEA Shalom Training College", category: "proprietary", region: "Nairobi" },
  { name: "Pioneer's Training Institute", category: "proprietary", region: "Nairobi" },
  { name: "PREMESE Africa Development Institute", category: "proprietary", region: "Nairobi" },
  {
    name: "Premier College of Hospitality and Business Studies",
    category: "proprietary",
    region: "Nairobi",
  },
  { name: "Premier College of Professional Studies", category: "proprietary", region: "Nairobi" },
  { name: "Prestige Academy and College", category: "proprietary", region: "Nakuru" },
  {
    name: "The Regional Institute of Business Management",
    category: "proprietary",
    region: "Nairobi",
  },
  {
    name: "Regional Centre for Tourism and Foreign Language",
    category: "proprietary",
    region: "Nairobi",
  },
  { name: "Regional Training Institute", category: "proprietary", region: "Nairobi" },
  { name: "Regions Group International College", category: "proprietary", region: "Nairobi" },
  {
    name: "Rift Valley Institute of Business Studies",
    category: "proprietary",
    region: "Nakuru / Kericho",
  },
  { name: "Rehoboth College", category: "proprietary", region: "Nairobi" },
  { name: "Riccatti Business College of East Africa", category: "proprietary", region: "Nairobi" },
  { name: "Rochester Business School", category: "proprietary", region: "Nairobi" },
  { name: "Royal Institute of Applied Sciences", category: "proprietary", region: "Meru" },
  { name: "Sacred Lake Institute of Technology", category: "proprietary", region: "Meru" },
  { name: "School of Professional Studies", category: "proprietary", region: "Nairobi" },
  { name: "Shalom Information Technology Centre", category: "proprietary", region: "Nairobi" },
  {
    name: "Shepherds Foundation Education & Research Centre",
    category: "proprietary",
    region: "Nairobi",
  },
  { name: "Skynet Business College", category: "proprietary", region: "Nairobi" },
  { name: "SMA Swiss Management Academy", category: "proprietary", region: "Nairobi" },
  { name: "Softpro Computer Institute", category: "proprietary", region: "Nairobi" },
  { name: "South Rift International College (SORICO)", category: "proprietary", region: "Kericho" },
  { name: "St. Andrew's Pre-Medical College", category: "proprietary", region: "Mombasa" },
  { name: "St. Joseph Vocational Training Centre", category: "proprietary", region: "Machakos" },
  { name: "Stanbridge College", category: "proprietary", region: "Taita Taveta" },
  { name: "Star Media Institute", category: "proprietary", region: "Nairobi" },
  { name: "Starnet College", category: "proprietary", region: "Nairobi" },
  { name: "Stonebic College", category: "proprietary", region: "Nairobi" },
  { name: "Superior Group of Colleges", category: "proprietary", region: "Nairobi" },
  { name: "Talent Institute", category: "proprietary", region: "Nairobi" },
  { name: "Tangaza College", category: "proprietary", region: "Nairobi" },
  { name: "Taznaam Tutorial College", category: "proprietary", region: "Nairobi" },
  { name: "Tec Institute of Management", category: "proprietary", region: "Nairobi / Uasin Gishu" },
  { name: "Thomas Asingo College", category: "proprietary", region: "Nairobi" },
  { name: "Times Training Centre", category: "proprietary", region: "Mombasa" },
  { name: "Universal Group of Colleges", category: "proprietary", region: "Nairobi" },
  {
    name: "Vision Institute of Professionals",
    category: "proprietary",
    region: "Nairobi / Mombasa",
  },
  { name: "Wang Point Technologies College", category: "proprietary", region: "Nairobi" },
  {
    name: "Western College of Hospitality and Professional Studies (Wechaps)",
    category: "proprietary",
    region: "Kisumu",
  },
  { name: "Zetech College", category: "proprietary", region: "Nairobi" },
  { name: "Kenyaplex Institute of Technology", category: "proprietary", region: "Machakos" },
];
